name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache
      uses: actions/cache@v3
      with:
        path: xtask/target
        key: xtask_build_cache

    - name: Build
      run: cargo xbuild -v
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Bootable Disk
        path: target/disk.img
